version: '3.7'

services:
  backend:
    container_name: backend
    image: remyfrancis510/backend:1.0
    environment:
      DB_host: mypostgresqlguigui
      DB_port: 5432
      DB_name: db
      DB_user: usr
      DB_mdp: pwd
    networks:
      - app-network
    depends_on:
      - database

  database:
    container_name: mypostgresqlguigui
    image: remyfrancis510/my_postgres:v1
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: usr
      POSTGRES_PASSWORD: pwd
    volumes:
      - postgresdata:/var/lib/postgresql/data
    networks:
      - app-network

  httpd:
    container_name: http
    image: remyfrancis510/serveur:1.0
    environment:
      BACKEND_host: backend
    ports:
      - "80:80"
    networks:
      - app-network
    depends_on:
      - backend

networks:
  app-network:


volumes:
  postgresdata:
